openapi: 3.0.0
info:
  title: Pieter AI Memory API
  version: 1.0.0
servers:
  - url: https://pieter-ai-full-memory.onrender.com
paths:
  /predict/:
    post:
      summary: Query Pieter's memory index
      operationId: queryPieterMemory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
